name: toby_in_dart
description: Toby trying out the Dart programming language hehe
version: 1.0.1
homepage: https://github.com/tobycm/toby-in-dart

environment:
  sdk: '>=2.18.7 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
